### ISSUE TITLE
lxc-ls segfaults on Fedora 26

### ISSUE THREAD

**Issue by jalbstmeijer** [ganto/copr-lxd#10]
Hi,

Followed the installation instructions and ended up with the following installed packages;

lxc-libs-2.1.0-0.1.fc26.x86_64
lxcfs-2.0.7-1.fc26.x86_64
lxd-tools-2.18-3.fc26.x86_64
libvirt-daemon-driver-lxc-3.2.1-6.fc26.x86_64
lxd-2.18-3.fc26.x86_64
libvirt-daemon-lxc-3.2.1-6.fc26.x86_64
python3-lxc-2.1.0-0.1.fc26.x86_64
lxc-2.0.8-2.fc26.x86_64
lxc-templates-2.1.0-0.1.fc26.x86_64
lxd-client-2.18-3.fc26.x86_64

result:

# lxc-ls
Segmentation fault (core dumped)

[11773.196526] lxc-ls[15027]: segfault at 18 ip 00007ff306946696 sp 00007fff9f80d080 error 4 in liblxc.so.1.3.0[7ff3068e3000+ac000]

Gr, J

**Comment by jalbstmeijer** [comment]
A 'yum upgrade" fixed it.
Somehow the upgrade of lxc-libs did not pull the new lxc package too.

**Comment by ganto** [comment]
Since you could resolve the problem by yourself and `lxd-2.18` is not the latest release anymore, I'll close this issue.
