### ISSUE TITLE
Starting the lxd.socket with SELinux fails with permission denied

### ISSUE THREAD

**Issue by ganto** [ganto/copr-lxd#12]
On a Fedora 27 with SELinux enabled, starting the LXD socket fails with a permission denied error:
```
# systemctl start lxd.socket
# systemctl status lxd.socket
● lxd.socket - LXD - unix socket                                                                                                                                          
   Loaded: loaded (/usr/lib/systemd/system/lxd.socket; enabled; vendor preset: disabled)                                                                                      
   Active: failed (Result: resources)                                                                                                                                          
     Docs: man:lxd(1)                                                                                                                                                     
   Listen: /var/lib/lxd/unix.socket (Stream)
                                                                                                                                                             
Apr 02 11:45:44 fedora27.example.com systemd[1]: lxd.socket: Failed to listen on sockets: Permission denied                                                               
Apr 02 11:45:44 fedora27.example.com systemd[1]: Failed to listen on LXD - unix socket.
Apr 02 11:45:44 fedora27.example.com systemd[1]: lxd.socket: Unit entered failed state.
```
The `/var/log/audit/audit.log` would show the following error:
```
type=AVC msg=audit(1522669544.856:959): avc:  denied  { create } for  pid=1 comm="systemd" name="unix.socket" scontext=system_u:system_r:init_t:s0 tcontext=system_u:object_r:var_lib_t:s0 tclass=sock_file permissive=0
```

**Comment by ganto** [comment]
The problem is obviously that SELinux prevents `systemd` from managing a Unix socket in `/var/lib/lxd/`. The following violations can be found in the log:
```
type=AVC msg=audit(1522696448.589:1006): avc:  denied  { create } for  pid=1 comm="systemd" name="unix.socket" scontext=system_u:system_r:init_t:s0 tcontext=system_u:object_r:var_lib_t:s0 tclass=sock_file permissive=1
type=AVC msg=audit(1522696986.822:1012): avc:  denied  { setattr } for  pid=11601 comm="systemd" name="unix.socket" dev="vda1" ino=1573050 scontext=system_u:system_r:init_t:s0 tcontext=system_u:object_r:var_lib_t:s0 tclass=sock_file permissive=1
type=AVC msg=audit(1522697574.451:1016): avc:  denied  { unlink } for  pid=1 comm="systemd" name="unix.socket" dev="vda1" ino=1573050 scontext=system_u:system_r:init_t:s0 tcontext=system_u:object_r:var_lib_t:s0 tclass=sock_file permissive=1
```

Although `container-selinux-2.38` already added some basic support for the correct LXD file system labels, it seems we are not quite there yet. LXD places the Unix socket in its application state directory which doesn't follow the common approach (e.g. used by `dockerd`) to place the socket into `/run` by default.

I managed to create the following local policy which would fix the issue:
* Create the following type enforcement policy file (`~/lxdsocketlocal.te`):
```
module lxdsocketlocal 1.0;

require {
        type container_var_lib_t;
        type init_t;
        class sock_file { create setattr unlink };
}
#============= init_t ==============
allow init_t container_var_lib_t:sock_file { create setattr unlink };
```
* Compile and load the new policy:
```
# checkmodule -M -m -o ~/lxdsocketlocal.mod ~/lxdsocketlocal.te
# mkdir -p /etc/selinux/targeted/modules/active/modules/
# semodule_package -o /etc/selinux/targeted/modules/active/modules/lxdsocketlocal.pp -m ~/lxdsocketlocal.mod
# semodule -i /etc/selinux/targeted/modules/active/modules/lxdsocketlocal.pp
```
* Afterwards the `lxd.socket` (and later `lxd.service`) can be started successfully:
```
# systemctl start lxd.socket
# getenforce
Enforcing
# systemctl status lxd.socket
● lxd.socket - LXD - unix socket
   Loaded: loaded (/usr/lib/systemd/system/lxd.socket; enabled; vendor preset: disabled)
   Active: active (running) since Fri 2018-04-06 05:55:14 UTC; 1min 2s ago
     Docs: man:lxd(1)
   Listen: /var/lib/lxd/unix.socket (Stream)

Apr 06 05:55:14 fedora27.example.com systemd[1]: Starting LXD - unix socket.
Apr 06 05:55:14 fedora27.example.com systemd[1]: Listening on LXD - unix socket.
```

**Comment by Conan-Kudo** [comment]
@stgraber, any particular reason why the socket is in `/var/lib/lxd` instead of `/run/lxd`? The latter is where I expect them to be...

**Comment by stgraber** [comment]
I suspect we did it because of multi-instance support, that is, in development we very frequently run multiple instances of LXD on the same machine. We also use this same feature when migrating data between non-snap and snap.

As the result, the LXD socket path is ${LXD_DIR}/unix.socket where LXD_DIR defaults to /var/lib/lxd/.
That variable and behavior is implemented in both the LXD daemon and client so that makes it pretty easy for users to run multiple daemons with different configurations.

**Comment by ganto** [comment]
@stgraber Thanks for your explanation. I didn't get that when glancing through the source code.

`$LXD_DIR` doesn't look very socket specific to me tough. Is there anything else depending on it that would break if it would be used to specify an alternative socket path?

**Comment by Conan-Kudo** [comment]
@stgraber Would it be possible to move it to `/var/run/lxd` without too much pain?

**Comment by ganto** [comment]
The new build `lxd-3.0.0-0.2` (https://github.com/ganto/copr-lxc3/commit/1b2c9560fc4500f26af15d908ab8f884dde4f194) from the [ganto/lxc3](https://copr.fedorainfracloud.org/coprs/ganto/lxc3) COPR repository is using the new `LXD_SOCKET` option which places the unix socket `/run/lxd.socket` and now fully works with SELinux :-)
