### ISSUE TITLE
After kernel update containers no longer running

### ISSUE THREAD

**Issue by shoodle** [ganto/copr-lxd#5]
A June 10th update installed the new **kernel.x86_64 4.11.3-202.fc25** on Fedora.

Since then the LXC containers won't start anymore (without error messages). But there is a LXD process:

```
/usr/bin/lxd waitready --timeout=600
```
lxd.log:

```
lvl=info msg="LXD 2.14 is starting in normal mode" path=/var/lib/lxd t=2017-06-11T11:11:48+0200
lvl=warn msg="AppArmor support has been disabled because of lack of kernel support" t=2017-06-11T11:11:48+0200
lvl=info msg="Kernel uid/gid map:" t=2017-06-11T11:11:48+0200
lvl=info msg=" - u 0 0 4294967295" t=2017-06-11T11:11:48+0200
lvl=info msg=" - g 0 0 4294967295" t=2017-06-11T11:11:48+0200
lvl=info msg="Configured LXD uid/gid map:" t=2017-06-11T11:11:48+0200
lvl=info msg=" - u 0 1000000 65536" t=2017-06-11T11:11:48+0200
lvl=info msg=" - g 0 1000000 65536" t=2017-06-11T11:11:48+0200
lvl=info msg="Updating the LXD database schema. Backup made as \"lxd.db.bak\"" t=2017-06-11T11:11:48+0200
```

**Comment by shoodle** [comment]
It was not an kernel issue but one of the updates for LXD on the 8th of June.

I had to downgrade lxd, lxd-client and lxd-tools to version 2.13-1.fc25.x86_64.

Now the containers are working again.

**Comment by ganto** [comment]
Yes, seems the initial `lxd-2.14` upstream release was a bit buggy. Unfortunately, I only noticed yesterday, that this is also the case with my RPM. In the meantime I added some patches according to the Ubuntu package and it seems to work for me again.

Can you please check, if you have the same issue with the `lxd-2.14-2` RPM?

**Comment by shoodle** [comment]
Thank you! When your release is in the repo I'll check it out.

**Comment by shoodle** [comment]
For me there is no difference with version 2.14-2. The containers are not running and I had to downgrade again.

**Comment by ganto** [comment]
Hmn, I'm running `lxd-2.14-2` with multiple containers on `kernel-4.11.5-100.fc24` without issues. Could you try to start the `lxd` daemon with the `--debug` option and see if you get more information about the error?

**Comment by shoodle** [comment]
First I updated to version 2.15. Containers no longer running.

```
[root@server ~]# lxd --debug
INFO[07-08|13:29:22] LXD 2.15 is starting in normal mode      path=/var/lib/lxd
WARN[07-08|13:29:22] AppArmor support has been disabled because of lack of kernel support 
INFO[07-08|13:29:22] Kernel uid/gid map: 
INFO[07-08|13:29:22]  - u 0 0 4294967295 
INFO[07-08|13:29:22]  - g 0 0 4294967295 
INFO[07-08|13:29:22] Configured LXD uid/gid map: 
INFO[07-08|13:29:22]  - u 0 1000000 65536 
INFO[07-08|13:29:22]  - g 0 1000000 65536 
INFO[07-08|13:29:22] Updating the LXD database schema. Backup made as "lxd.db.bak" 
DBUG[07-08|13:29:22] Updating DB schema from 35 to 36 
error: duplicate column name: description
```

The main problem I have now: I cannot downgrade any longer to version 2.13: No packages available.

What should I do now?

**Comment by ganto** [comment]
Ok, seems that one of the updates somehow confused your database.

Downgrading is generally not officially supported but I still uploaded the old RPMs for you in case you want to try. You can find the packages at: https://linuxmonk.ch/copr/archive/.

When downgrading, stop the service, make sure to create a backup of `/var/lib/lxd/lxd.db`, copy back the `/var/lib/lxd/lxd.db.bak` (automated backup before the upgrade) and then only downgrade the package and restart the service.

If this doesn't work, then I would suggest to simply start with a clean installation or ask in the upstream project (mailing list or github) for assistance. The community is very supportive and @stgraber also help me to recover a messed up database before.

Good luck

**Comment by shoodle** [comment]
Thank you for uploading the old RPMs. Now the containers are running again.

It seems what you said about the lxd-2.14 release ("was a bit buggy") was the cause for my problems now.

**Comment by shoodle** [comment]
https://github.com/lxc/lxd/issues/3513: issue solved.
