### ISSUE TITLE
installing lxd from dnf copr fails

### ISSUE THREAD

**Issue by linuxownz** [ganto/copr-lxd#9]
Hi,
  I am trying to install lxd on fedora 26 via 
dnf install lxd lxd-client lxd-tools

It fails with 
Copr repo for lxd owned by ganto      
Error: 
 Problem: conflicting requests
  - nothing provides lxc-libs >= 2.1.0 needed by lxd-2.18-3.fc26.x86_64

Since its the first time im trying to install from copr, this might be a PEBKAC issue.  Any help appreciated.

**Comment by iaroki** [comment]
In addition to LXD copr you need to enable LXC copr:
```
dnf copr enable ganto/lxc
```
`lxd` packages depends on the newer versions of `lxc`

**Comment by ganto** [comment]
The latest update (`lxd-2.20`) should not depend on `>=lxc-libs-2.1.0` anymore and therefore work again with the default `lxc-libs` from Fedora. If you want a newer one, you still can optionally enable the `ganto/lxc` COPR repository.
